### ISSUE TITLE
 Error occurred while disabling AstraRating v1.20.0

### ISSUE THREAD

**Issue by IsNott** [Astra-Interactive/AstraRating#47]
plugin-version: AstraRating-1.20.0
minecraft server:purpur 1.20.4
os: Windows10
Full plugin loding error log:
[11:22:12] [Server thread/ERROR]: Error occurred while enabling AstraRating v1.20.0 (Is it up to date?)
java.io.IOException: 系统找不到指定的路径。
	at java.io.WinNTFileSystem.createFileExclusively0(Native Method) ~[?:?]
	at java.io.WinNTFileSystem.createFileExclusively(WinNTFileSystem.java:569) ~[?:?]
	at java.io.File.createNewFile(File.java:1045) ~[?:?]
	at ru.astrainteractive.astrarating.core.di.CoreModule$Default$special$$inlined$create$1.loadAndGet(ConfigKrateFactory.kt:26) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.klibs.kstorage.api.impl.DefaultStateFlowMutableKrate.<init>(DefaultStateFlowMutableKrate.kt:26) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.klibs.kstorage.api.impl.DefaultStateFlowMutableKrate.<init>(DefaultStateFlowMutableKrate.kt:18) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.core.di.CoreModule$Default.<init>(CoreModule.kt:71) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.di.RootModule$Default.coreModule_delegate$lambda$1(RootModule.kt:43) ~[AstraRating-1.20.0.jar:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.di.RootModule$Default.getCoreModule(RootModule.kt:42) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.di.RootModule$Default.getLifecycles(RootModule.kt:109) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.di.RootModule$Default.lifecycle$lambda$10(RootModule.kt:120) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astralibs.lifecycle.Lifecycle$Lambda.onEnable(Lifecycle.kt:17) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.AstraRating.onEnable(AstraRating.kt:9) ~[AstraRating-1.20.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
[11:22:12] [Server thread/INFO]: [AstraRating] Disabling AstraRating v1.20.0
[11:22:12] [Server thread/ERROR]: Error occurred while disabling AstraRating v1.20.0
java.io.IOException: 系统找不到指定的路径。
	at java.io.WinNTFileSystem.createFileExclusively0(Native Method) ~[?:?]
	at java.io.WinNTFileSystem.createFileExclusively(WinNTFileSystem.java:569) ~[?:?]
	at java.io.File.createNewFile(File.java:1045) ~[?:?]
	at ru.astrainteractive.astrarating.core.di.CoreModule$Default$special$$inlined$create$1.loadAndGet(ConfigKrateFactory.kt:26) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.klibs.kstorage.api.impl.DefaultStateFlowMutableKrate.<init>(DefaultStateFlowMutableKrate.kt:26) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.klibs.kstorage.api.impl.DefaultStateFlowMutableKrate.<init>(DefaultStateFlowMutableKrate.kt:18) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.core.di.CoreModule$Default.<init>(CoreModule.kt:71) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.di.RootModule$Default.coreModule_delegate$lambda$1(RootModule.kt:43) ~[AstraRating-1.20.0.jar:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.di.RootModule$Default.getCoreModule(RootModule.kt:42) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.di.RootModule$Default.getLifecycles(RootModule.kt:109) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.di.RootModule$Default.lifecycle$lambda$12(RootModule.kt:122) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astralibs.lifecycle.Lifecycle$Lambda.onDisable(Lifecycle.kt:21) ~[AstraRating-1.20.0.jar:?]
	at ru.astrainteractive.astrarating.AstraRating.onDisable(AstraRating.kt:13) ~[AstraRating-1.20.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by makeevrserg** [comment]
@IsNott Thank you, will be fixed in 1.20.1 after #48
